#!/usr/bin/env python3
"""Status dashboard — serve, validate, render. Portable across projects.

Single source of truth = status.json. Cowork edits that file; you flip statuses from the page.
Stdlib only, no dependencies.

  python3 status.py                 # serve the editable dashboard (default)
  python3 status.py --check         # VALIDATE the board; non-zero exit on any error
  python3 status.py --render        # regenerate queue.md from status.json
  python3 status.py --render --check-sync   # fail if queue.md is stale vs status.json
  python3 status.py --dir path/to/Strategy   # run against a board elsewhere (default: this folder)

WHAT'S PROJECT-SPECIFIC lives in status.json (`project`, `subtitle`, `modules`) — nothing about a
particular product is hard-coded here, so this drops into any repo unchanged.

WHY --check EXISTS (the load-bearing part):
A tracker that nobody verifies is a rumour. Our previous tracker rotted into a 2,500-line lie —
`grep` reported 21 pending rounds when 3 were real — because *nothing ever checked it*. Rendering a
dashboard over an unchecked file just renders the lie faithfully, in colour. So the script validates:
dangling blockers, dependency cycles, `ref` files that don't exist, duplicate ids, done-items still
blocking others, and staleness. It exits non-zero so it can be a git hook or a Stop-hook gate.
"""
import argparse
import datetime
import json
import os
import subprocess
import sys
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_ROOT = os.path.dirname(HERE)            # parent of Strategy/ = the workspace root
DATA = os.path.join(HERE, "status.json")
PAGE = os.path.join(HERE, "STATUS.html")
QUEUE = os.path.join(HERE, "queue.md")
ALLOWED_STATUS = {"done", "active", "pending", "deferred"}
EDITOR = os.environ.get("ABP_EDITOR", "")  # e.g. "WebStorm", "Code"; --editor overrides
_lock = threading.Lock()

GENERATED_BANNER = "<!-- GENERATED by status.py --render — DO NOT EDIT. Source of truth: status.json -->"


# ---------------------------------------------------------------- data

def _read():
    with open(DATA, encoding="utf-8") as f:
        return json.load(f)


def _write(doc):
    doc["last_updated"] = datetime.date.today().isoformat()
    tmp = DATA + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
        f.write("\n")
    os.replace(tmp, DATA)  # atomic


def _by_id(items):
    return {it["id"]: it for it in items}


def blockers_of(item, index):
    """The UNMET blockers of an item: ids in `blocked_by` whose item isn't done.
    A blocker that doesn't resolve is reported by --check, not silently ignored."""
    out = []
    for b in item.get("blocked_by") or []:
        dep = index.get(b)
        if dep is None or dep.get("status") != "done":
            out.append(b)
    return out


def is_blocked(item, index):
    return item.get("status") in ("pending", "active") and bool(blockers_of(item, index))


# ---------------------------------------------------------------- validate

def check(doc, quiet=False):
    """Validate the board. Returns (errors, warnings). This is the test the old tracker never had."""
    items = doc.get("items", [])
    index = _by_id(items)
    errors, warns = [], []

    # duplicate ids — two rows claiming to be the same fact
    seen = set()
    for it in items:
        if it["id"] in seen:
            errors.append(f"duplicate id: {it['id']}")
        seen.add(it["id"])

    modules = set(doc.get("modules") or [])
    for it in items:
        iid = it["id"]

        if it.get("status") not in ALLOWED_STATUS:
            errors.append(f"{iid}: bad status {it.get('status')!r}")
        if modules and it.get("module") not in modules:
            errors.append(f"{iid}: module {it.get('module')!r} not in modules[]")

        # a blocker must RESOLVE. A dangling blocker means an item is silently unblocked.
        for b in it.get("blocked_by") or []:
            if b not in index:
                errors.append(f"{iid}: blocked_by '{b}' does not exist")

        # a DRAFTED round must have a prompt file that actually exists on disk. This is the check
        # that would have caught rounds sitting 'ready' whose prompt was never written.
        if it.get("type") == "round" and it.get("drafted") and it.get("ref"):
            if not _safe_abspath(it["ref"]):
                errors.append(f"{iid}: drafted, but ref '{it['ref']}' does not resolve to a file")

        # any ref should resolve to a file OR a directory (a doc job may point at a folder)
        if it.get("ref") and not _safe_path(it["ref"]):
            if not (it.get("type") == "round" and it.get("drafted")):
                warns.append(f"{iid}: ref '{it['ref']}' does not resolve")

        # a DONE item that still lists unmet blockers is incoherent
        if it.get("status") == "done":
            unmet = blockers_of(it, index)
            if unmet:
                errors.append(f"{iid}: marked done but still blocked by {unmet}")

        # an ACTIVE item that is blocked is a lie — it cannot be in progress
        if it.get("status") == "active" and blockers_of(it, index):
            errors.append(f"{iid}: ACTIVE but blocked by {blockers_of(it, index)} — it cannot be in progress")

        # a parked item with no reason gets deleted; if we can't say why it waits, it isn't real work
        if it.get("status") == "deferred" and not (it.get("note") or "").strip():
            errors.append(f"{iid}: deferred with NO reason — say why it waits or delete it")

    # dependency cycles
    def cycle_from(start):
        seen_, stack = set(), [(start, [start])]
        while stack:
            cur, path = stack.pop()
            for b in index.get(cur, {}).get("blocked_by") or []:
                if b == start:
                    return path + [b]
                if b in index and b not in seen_:
                    seen_.add(b)
                    stack.append((b, path + [b]))
        return None

    reported = set()
    for it in items:
        c = cycle_from(it["id"])
        if c and frozenset(c) not in reported:
            reported.add(frozenset(c))
            errors.append(f"dependency CYCLE: {' → '.join(c)}")

    # cross-check the presence board: a running round must match an IN PROGRESS row, and vice versa.
    # The REVERSE direction is the one you'd never think to look for.
    #
    # NB: match only TABLE ROWS (lines starting with '|'). A naive substring search over the whole
    # file matches current.md's own documentation prose ("a session sets its row to `IN PROGRESS`…")
    # and reports drift that isn't there — this checker's first run did exactly that.
    cur_md = os.path.join(SRC_ROOT, "current.md")
    if os.path.isfile(cur_md):
        try:
            rows_ = [ln for ln in open(cur_md, encoding="utf-8", errors="replace")
                     if ln.lstrip().startswith("|")]
            in_progress = [ln for ln in rows_ if "IN PROGRESS" in ln]
            actives = [i["id"] for i in items if i.get("type") == "round" and i.get("status") == "active"]
            if actives and not in_progress:
                warns.append(f"round(s) {actives} are ACTIVE but no current.md ROW says IN PROGRESS")
            if in_progress and not actives:
                warns.append(f"{len(in_progress)} current.md row(s) say IN PROGRESS but no round is "
                             f"ACTIVE — drift in the direction nobody checks")
        except OSError:
            pass

    if not quiet:
        for e in errors:
            print(f"  ERROR  {e}")
        for w in warns:
            print(f"  warn   {w}")
        n_items = len(items)
        if errors:
            print(f"\n✗ {len(errors)} error(s), {len(warns)} warning(s) over {n_items} items.")
        else:
            print(f"✓ board is coherent — {n_items} items, {len(warns)} warning(s).")
    return errors, warns


# ---------------------------------------------------------------- render queue.md

def render_queue(doc):
    """Render the LIVE board to markdown. Committed so Claude Code sessions can read it at boot
    without running anything. Done items are RETAINED in status.json (history — an ops gate has no
    other record) but EXCLUDED here: the board a session reads shows only work that is still real."""
    items = doc.get("items", [])
    index = _by_id(items)
    rounds = [i for i in items if i.get("type") == "round"]
    gates = [i for i in items if i.get("type") in ("ops", "launch")]
    docs = [i for i in items if i.get("type") == "doc"]

    live = [i for i in rounds if i.get("status") == "active" and not is_blocked(i, index)]
    ready = [i for i in rounds if i.get("status") == "pending" and i.get("drafted")
             and not is_blocked(i, index)]
    blocked = [i for i in rounds if is_blocked(i, index) and i.get("status") != "deferred"]
    backlog = [i for i in rounds if i.get("status") == "pending" and not i.get("drafted")
               and not is_blocked(i, index)]
    parked = [i for i in rounds if i.get("status") == "deferred"]
    open_gates = [i for i in gates if i.get("status") != "done"]
    open_docs = [i for i in docs if i.get("status") != "done"]

    L = [GENERATED_BANNER, "",
         f"# {doc.get('project','')} — round queue",
         "",
         "**Generated from `status.json`. Do not edit this file** — run `python3 status.py --render`.",
         "Status lives in exactly one place. `ledger.md` is the archive (what each round did and why); it",
         "carries no status. A shipped round leaves this board; its record stays in `status.json` + the ledger.",
         "",
         f"*Last updated {doc.get('last_updated','?')}.*", ""]

    def rows(lst, cols, fn):
        L.append("| " + " | ".join(cols) + " |")
        L.append("|" + "|".join("---" for _ in cols) + "|")
        for i in lst:
            L.append("| " + " | ".join(fn(i)) + " |")
        L.append("")

    def note(i, n=190):
        t = (i.get("note") or "").replace("|", "\\|").replace("\n", " ")
        return (t[:n] + "…") if len(t) > n else t

    L += ["## 🔴 LIVE — a session is running", ""]
    if live:
        rows(live, ["Round", "Module", "Notes"], lambda i: [f"**{i['id']}**", i["module"], note(i)])
    else:
        L += ["*(none)*", ""]

    L += ["## 🟢 READY — drafted, launchable now", ""]
    if ready:
        rows(ready, ["Round", "Module", "Prompt", "Notes"],
             lambda i: [f"**{i['id']}**", i["module"], f"`{i.get('ref','')}`", note(i)])
    else:
        L += ["*(none)*", ""]

    L += ["## 🟡 BLOCKED — waiting on something specific", ""]
    if blocked:
        rows(blocked, ["Round", "Module", "Blocked by"],
             lambda i: [f"**{i['id']}**", i["module"],
                        ", ".join(f"**{b}** ({index[b]['title']})" if b in index else f"**{b}** ⚠ unknown"
                                  for b in blockers_of(i, index))])
    else:
        L += ["*(none)*", ""]

    L += ["## 🚦 GATES — human/external, and nothing else records them", "",
          "*An engine tag, a deploy, a migration, a store approval. These have **no git commit and no code to",
          "grep** — delete one and it is simply gone. They stay on the board until they are done.*", ""]
    if open_gates:
        rows(open_gates, ["Gate", "Module", "Owner", "Notes"],
             lambda i: [f"**{i['id']}** — {i['title']}", i["module"], i.get("owner", "—"), note(i)])
    else:
        L += ["*(none open)*", ""]

    L += ["## 🔵 BACKLOG — real work, not yet drafted into a prompt", ""]
    if backlog:
        rows(backlog, ["Item", "Module", "Notes"], lambda i: [f"**{i['id']}** — {i['title']}", i["module"], note(i)])
    else:
        L += ["*(none)*", ""]

    L += ["## ⏸️ PARKED — deliberately not scheduled, with the reason", "",
          "*Every parked row states its reason. A parked item with no reason gets deleted — if we can't say what",
          "it's waiting for, it isn't real work. (`--check` enforces this.)*", ""]
    if parked:
        rows(parked, ["Item", "Why it is parked"], lambda i: [f"**{i['id']}** — {i['title']}", note(i, 260)])
    else:
        L += ["*(none)*", ""]

    L += ["## 📓 COWORK — not rounds; the orchestrator's own work", ""]
    if open_docs:
        rows(open_docs, ["Item", "Notes"], lambda i: [f"**{i['id']}** — {i['title']}", note(i)])
    else:
        L += ["*(none)*", ""]

    return "\n".join(L).rstrip() + "\n"


# ---------------------------------------------------------------- editor plumbing (unchanged)

def _resolve(rel):
    """Resolve a `ref` (relative to Strategy/) to an absolute path INSIDE the workspace root, or
    None. Guards against path traversal. Existence is the caller's question."""
    if not rel:
        return None
    p = os.path.realpath(os.path.join(HERE, rel))
    root = os.path.realpath(SRC_ROOT)
    if p != root and not p.startswith(root + os.sep):
        return None
    return p


def _safe_abspath(rel):
    """A ref that resolves to an existing FILE (the editor-open path needs a file)."""
    p = _resolve(rel)
    return p if p and os.path.isfile(p) else None


def _safe_path(rel):
    """A ref that resolves to an existing file OR DIRECTORY. A doc job may legitimately point at a
    folder (e.g. `../docs/videos`) — demanding isfile() there reports a phantom broken ref."""
    p = _resolve(rel)
    return p if p and os.path.exists(p) else None


def _line_for_section(path, sec):
    """Resolve a `sec` label to a 1-based line by SCANNING. No stored line numbers = no drift."""
    needle = (sec or "").strip().lstrip("§").strip().lower()
    if not needle:
        return None
    first_hit = None
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            for i, line in enumerate(f, 1):
                if needle in line.lower():
                    if first_hit is None:
                        first_hit = i
                    s = line.lstrip()
                    if s.startswith("#") or s.startswith("- ") or s.startswith("* "):
                        return i
    except OSError:
        return None
    return first_hit


def _open_app(target):
    try:
        r = subprocess.run(["open", "-a", EDITOR, target], capture_output=True, text=True)
        return (r.returncode == 0), (r.stderr or "").strip()
    except FileNotFoundError:
        return False, "'open' not found (this opener is macOS-only)"


def _cli_open(target, line=None):
    cli = EDITOR.lower()
    cmd = [cli] + (["--line", str(line)] if line else []) + [target]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True)
        return (r.returncode == 0), (r.stderr or "").strip()
    except FileNotFoundError:
        return False, f"'{cli}' CLI not found"


def _open_in_editor(target, line=None):
    if line:
        ok, _ = _cli_open(target, line)
        if ok:
            return True, ""
        ok2, err2 = _open_app(target)
        if ok2:
            return True, ("opened without jumping to line — install the WebStorm CLI "
                          "(JetBrains Toolbox → generate shell scripts) for line jumps")
        return False, err2
    ok, err = _open_app(target)
    if ok:
        return True, ""
    ok2, err2 = _cli_open(target)
    return (True, "") if ok2 else (False, err or err2)


# ---------------------------------------------------------------- server

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def _send(self, code, body, ctype="application/json"):
        if isinstance(body, str):
            body = body.encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = self.path.split("?", 1)[0]
        if path in ("/", "/STATUS.html", "/index.html"):
            with open(PAGE, "rb") as f:
                return self._send(200, f.read(), "text/html; charset=utf-8")
        if path == "/status.json":
            with open(DATA, "rb") as f:
                return self._send(200, f.read(), "application/json")
        if path == "/check":
            errors, warns = check(_read(), quiet=True)
            return self._send(200, json.dumps({"errors": errors, "warnings": warns}))
        if path == "/open":
            q = parse_qs(urlparse(self.path).query)
            rel = (q.get("path") or [""])[0]
            sec = (q.get("sec") or [""])[0]
            target = _safe_abspath(rel)
            if not target:
                return self._send(400, json.dumps({"error": "bad or out-of-tree path"}))
            line = _line_for_section(target, sec)
            ok, msg = _open_in_editor(target, line)
            if ok:
                print(f"  · open {EDITOR}: {os.path.relpath(target, SRC_ROOT)}" + (f":{line}" if line else ""))
                return self._send(200, json.dumps({"ok": True, **({"note": msg} if msg else {})}))
            return self._send(500, json.dumps({"error": msg}))
        return self._send(404, json.dumps({"error": "not found"}))

    def do_POST(self):
        if self.path != "/api/update":
            return self._send(404, json.dumps({"error": "not found"}))
        try:
            n = int(self.headers.get("Content-Length", 0))
            req = json.loads(self.rfile.read(n) or b"{}")
        except Exception as e:
            return self._send(400, json.dumps({"error": f"bad json: {e}"}))
        item_id, status = req.get("id"), req.get("status")
        if status not in ALLOWED_STATUS:
            return self._send(400, json.dumps({"error": "bad status"}))
        with _lock:
            doc = _read()
            hit = next((it for it in doc["items"] if it["id"] == item_id), None)
            if not hit:
                return self._send(404, json.dumps({"error": "unknown id"}))
            # REFUSE to mark a blocked item active — the dashboard must not let you lie to yourself.
            if status == "active":
                unmet = blockers_of(hit, _by_id(doc["items"]))
                if unmet:
                    return self._send(409, json.dumps(
                        {"error": f"blocked by {', '.join(unmet)} — resolve those first"}))
            hit["status"] = status
            _write(doc)
            # keep the rendered board in lock-step with the source, automatically
            with open(QUEUE, "w", encoding="utf-8") as f:
                f.write(render_queue(doc))
            print(f"  · {item_id} → {status}   (queue.md re-rendered)")
            return self._send(200, json.dumps({"ok": True, "last_updated": doc["last_updated"]}))


def main():
    global EDITOR, HERE, SRC_ROOT, DATA, PAGE, QUEUE
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=None,
                    help="folder holding status.json/STATUS.html (default: this script's folder)")
    ap.add_argument("--port", type=int, default=8787)
    ap.add_argument("--no-open", action="store_true")
    ap.add_argument("--editor", default=EDITOR, help="editor to open refs in (e.g. WebStorm, Code); or set ABP_EDITOR")
    ap.add_argument("--check", action="store_true", help="validate the board; non-zero exit on error")
    ap.add_argument("--render", action="store_true", help="regenerate queue.md from status.json")
    ap.add_argument("--check-sync", action="store_true", help="with --render: fail if queue.md is stale")
    args = ap.parse_args()
    EDITOR = args.editor
    if args.dir:
        HERE = os.path.abspath(args.dir)
        SRC_ROOT = os.path.dirname(HERE)
        DATA = os.path.join(HERE, "status.json")
        PAGE = os.path.join(HERE, "STATUS.html")
        QUEUE = os.path.join(HERE, "queue.md")
    doc = _read()

    if args.render:
        out = render_queue(doc)
        if args.check_sync:
            cur = open(QUEUE, encoding="utf-8").read() if os.path.isfile(QUEUE) else ""
            if cur != out:
                print("✗ queue.md is STALE — run: python3 status.py --render")
                sys.exit(1)
            print("✓ queue.md is in sync with status.json")
        else:
            with open(QUEUE, "w", encoding="utf-8") as f:
                f.write(out)
            print(f"✓ wrote {os.path.relpath(QUEUE, SRC_ROOT)}")
        if not args.check:
            return

    if args.check:
        errors, _ = check(doc)
        sys.exit(1 if errors else 0)

    url = f"http://127.0.0.1:{args.port}/"
    srv = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"{doc.get('project','status')} dashboard → {url}  (Ctrl-C to stop)")
    errs, warns = check(doc, quiet=True)
    if errs:
        print(f"  ⚠ {len(errs)} error(s) on the board — see the banner, or run --check")
    if not args.no_open:
        threading.Timer(0.4, lambda: webbrowser.open(url)).start()
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")


if __name__ == "__main__":
    main()
